// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'feature/conver_currency_feature/data/models/list_supported_country_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 82386705906531723),
      name: 'ListSupportedCountryModel',
      lastPropertyId: const IdUid(2, 7647516746994034798),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1971975311776481133),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7647516746994034798),
            name: 'supportedCurrencies',
            type: 30,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 82386705906531723),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ListSupportedCountryModel: EntityDefinition<ListSupportedCountryModel>(
        model: _entities[0],
        toOneRelations: (ListSupportedCountryModel object) => [],
        toManyRelations: (ListSupportedCountryModel object) => {},
        getId: (ListSupportedCountryModel object) => object.id,
        setId: (ListSupportedCountryModel object, int id) {
          object.id = id;
        },
        objectToFB: (ListSupportedCountryModel object, fb.Builder fbb) {
          final supportedCurrenciesOffset = fbb.writeList(object
              .supportedCurrencies
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, supportedCurrenciesOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ListSupportedCountryModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              supportedCurrencies: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 6, []));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ListSupportedCountryModel] entity fields to define ObjectBox queries.
class ListSupportedCountryModel_ {
  /// see [ListSupportedCountryModel.id]
  static final id = QueryIntegerProperty<ListSupportedCountryModel>(
      _entities[0].properties[0]);

  /// see [ListSupportedCountryModel.supportedCurrencies]
  static final supportedCurrencies =
      QueryStringVectorProperty<ListSupportedCountryModel>(
          _entities[0].properties[1]);
}
